spring:
  application:
    name: hk-stock-trading-system
    version: 1.0.0
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:h2:file:./data/trading_db;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Hong_Kong
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 100
      thread-name-prefix: async-
    scheduling:
      pool:
        size: 4
      thread-name-prefix: scheduled-
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  shutdown: graceful
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}

# Trading System Configuration
trading:
  system:
    name: "HK Stock Trading System"
    timezone: "Asia/Hong_Kong"
    
  capital:
    total: 100000
    currency: "HKD"
    max-position: 50000
    max-positions-count: 3
    
  risk:
    max-daily-loss: 0.05      # 最大日亏损5%
    max-drawdown: 0.15        # 最大回撤15%
    risk-per-trade: 0.02      # 单笔风险2%
    stop-loss-atr: 2.0        # ATR止损倍数
    
  targets:
    - symbol: "2800.HK"
      name: "Tracker Fund"
      type: "ETF"
      weight: 0.4
      lot-size: 500
    - symbol: "3033.HK"
      name: "Hang Seng Tech ETF"
      type: "ETF"
      weight: 0.3
      lot-size: 100
    - symbol: "00700.HK"
      name: "Tencent"
      type: "STOCK"
      weight: 0.3
      lot-size: 100
      
  timeframes:
    primary: "30m"
    confirmation: "120m"
    
  execution:
    mode: "PAPER"              # PAPER/LIVE
    slippage: 0.001           # 滑点0.1%
    commission: 0.0005        # 佣金0.05%
    min-commission: 5.0       # 最低佣金5港币
    
  market-hours:
    pre-market:
      start: "09:00"
      end: "09:30"
    morning:
      start: "09:30"
      end: "12:00"
    afternoon:
      start: "13:00"
      end: "16:00"
    
  # Strategy Configuration
  strategies:
    macd:
      enabled: true
      weight: 0.35
      fast-period: 12
      slow-period: 26
      signal-period: 9
      histogram-threshold: 0.002
      
    bollinger:
      enabled: true
      weight: 0.35
      period: 20
      std-dev: 2.0
      squeeze-threshold: 0.015

    bollinger-band:
      enabled: true
      # 自适应策略使用的多套布林带参数
      parameter-sets:
        - key: "ranging"  # 盘整市：标准参数
          period: 20
          std-dev: 2.0
        - key: "trending" # 趋势市：收紧参数，更灵敏
          period: 10
          std-dev: 1.5
        - key: "volatile" # 高波动：放宽参数，减少噪音
          period: 30
          std-dev: 2.5
      # 自适应策略本身的参数
      adaptive:
        enabled: true
        # 趋势识别的ADX阈值 (经2024年数据分析, 从25下调)
        adx-threshold: 22.0
        # 盘整市识别的ATR比率阈值 (经2024年数据分析, 从0.015下调)
        atr-ratio-threshold: 0.010

        # 缓冲因子 (经2024年数据分析后优化)
        ranging-lower-buffer-factor: 1.002 # 盘整市买入缓冲 (更接近下轨)
        ranging-upper-buffer-factor: 0.998 # 盘整市卖出缓冲 (更接近上轨)
        trending-middle-buffer-factor: 1.005 # 趋势市突破中轨缓冲
        trending-upper-limit-factor: 1.02  # 趋势市上轨限制因子(>1.0则基本等同于放开限制)

        trending-params-key: "trending"
        ranging-params-key: "ranging"
        volatile-params-key: "volatile"
      # 均值回归子策略 (可被自适应策略调用)
      mean-reversion:
        enabled: true
        min-buy-score: 80
        position-size-ratio: 0.95
        expansion-threshold: 1.5
      # 挤压突破子策略 (可被自适应策略调用)
      squeeze-breakout:
        enabled: true
        squeeze-threshold: 0.015
        min-squeeze-periods: 5
        breakout-lookback: 10
        expansion-factor: 0.2
        volume-multiplier: 1.5  # 突破时成交量需要放大1.5倍
      
    volume:
      enabled: true
      weight: 0.30
      spike-ratio: 1.8
      decline-ratio: 0.7
      vwap-deviation: 0.02
      
  # Four-Layer Filter System
  filters:
    volatility:
      min-atr: 0.005          # 最小ATR 0.5%
      max-atr: 0.05           # 最大ATR 5%
    volume:
      min-ratio: 1.2          # 最小量比
      min-turnover: 1000000   # 最小成交额100万
    trend:
      confirmation-period: "120m"
      min-strength: 0.6
    risk:
      max-position-pct: 0.3   # 单个仓位最大30%
      max-correlation: 0.7    # 最大相关性

logging:
  level:
    root: INFO
    com.trading: DEBUG
    org.springframework: INFO
    org.hibernate: WARN
    com.lmax.disruptor: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/trading-system.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB